apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-cip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-cip
  template:
    metadata:
      labels:
      app: my-app-cip
spec:
  containers:
  -name: my-container
  image: nginx:latest
  ports:
  - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-cip
  labels:
    app: my-app-cip
spec:
  type : ClusterIp
  ports:
  - port: 80
    protocal: TCP
  selector:
  run: my-app-cip  

