apiVersion: apps/v1
kind: Replicaset
metadata:
name: my-replicaset
spec:
replicas: 3
selector:
matchLables:
app: my-app
template:
metadata:
lables:
app: my-app
spec:
containers:
-name: my-container
image: nginx:latest
ports:
-containerPort: 8080